name: places
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

  flutter_svg: ^0.19.2+1

  sprintf: "^4.0.0"

  provider: ^4.3.3 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/icon/
  
  fonts: 
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-Regular.ttf
  